package demo.except;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

public class FileReading {

	public static void main(String[] args) {

	  try {
		  
		  System.out.println(5/0);
		  
	  }catch(Exception e) {
		  
		  System.out.println("Inside the catch block after the exception.");
		  
		  throw new ArithmeticException("Division is not valid.");
	  }

	}

}
